//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        public string TimeWorkNo { get; set; }
        public string TimeWork { get; set; }
        public Nullable<double> Allowance1 { get; set; }
    }
}
