//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDB.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpNo { get; set; }
        public string FullName { get; set; }
        public string Sex { get; set; }
        public string DOB { get; set; }
        public string Job { get; set; }
        public string Locations { get; set; }
    }
}
